export default [
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "GSM本地小区能力下降告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "GSM本地小区能力下降告警",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "BASE STATION NOTIFICATION",
    n2: "bts",
    n3: "CELL FAULTY",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BASE STATION OPERATION DEGRADED",
    n2: "bts",
    n3: "BASE STATION NOTIFICATION",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BASE STATION OPERATION DEGRADED",
    n2: "bts",
    n3: "CELL FAULTY",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BBU CPRI光接口性能恶化告警",
    n2: "bts",
    n3: "GSM本地小区能力下降告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BBU CPRI光接口性能恶化告警",
    n2: "bts",
    n3: "GSM本地小区能力下降告警",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "BBU CPRI光接口性能恶化告警",
    n2: "bts",
    n3: "载波无话务量告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BBU CPRI光模块/电接口不在位告警",
    n2: "bts",
    n3: "BBU CPRI接口异常告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BBU CPRI光模块/电接口不在位告警",
    n2: "bts",
    n3: "CXU维护链路异常告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "CXU维护链路异常告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "CXU维护链路异常告警",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "BASE STATION NOTIFICATION",
    n2: "bts",
    n3: "CXU维护链路异常告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BASE STATION OPERATION DEGRADED",
    n2: "bts",
    n3: "CXU维护链路异常告警",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "BASE STATION NOTIFICATION",
    n2: "bts",
    n3: "BBU CPRI接口异常告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BASE STATION OPERATION DEGRADED",
    n2: "bts",
    n3: "BBU CPRI接口异常告警",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "BBU CPRI接口异常告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "BBU CPRI接口异常告警",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "载波无话务量告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "载波无话务量告警",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "BASE STATION NOTIFICATION",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "Abis控制端口故障告警",
    n2: "bts",
    n3: "BASE STATION NOTIFICATION",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "BASE STATION NOTIFICATION",
    n2: "bts",
    n3: "载波无话务量告警",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BASE STATION OPERATION DEGRADED",
    n2: "bts",
    n3: "载波无话务量告警",
    n4: "cell",
    n5: "跨域",
  },
  {
    n1: "BASE STATION NOTIFICATION",
    n2: "bts",
    n3: "BASE STATION NOTIFICATION",
    n4: "bts",
    n5: "单域",
  },
  {
    n1: "BASE STATION OPERATION DEGRADED",
    n2: "bts",
    n3: "BASE STATION NOTIFICATION",
    n4: "cell",
    n5: "跨域",
  },
];
